name: 直播间抽奖

on:

    workflow_dispatch:

    schedule:

        - cron: '0 0-16/1 * * *'

    watch:

        types: [started]

    repository_dispatch:

        types: jd_live_lottery_social

jobs:

    build:

        runs-on: ubuntu-latest

        if: github.event.repository.owner.id == github.event.sender.id

        steps:

            - uses: actions/checkout@v1

            - name: Use Node.js 10.x

              uses: actions/setup-node@v1

              with:

                  node-version: 10.x

            - name: npm install

              run: |
                  npm install
            - name: "运行 【直播间抽奖】"

              run: |
                  node jd_live_lottery_social.js
              env:

                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}

                  JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }}

                  JD_USER_AGENT: ${{ github.event.client_payload.JD_USER_AGENT || secrets.JD_USER_AGENT }}

                  PUSH_PLUS_TOKEN: ${{ github.event.client_payload.PUSH_PLUS_TOKEN || secrets.PUSH_PLUS_TOKEN }}

                  PUSH_PLUS_USER: ${{ github.event.client_payload.PUSH_PLUS_USER || secrets.PUSH_PLUS_USER }}

                  JD_CASH_SHARECODES: ${{ github.event.client_payload.JD_CASH_SHARECODES || secrets.JD_CASH_SHARECODES }}

